spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping?serverTimezone=GMT%2b8&amp;useUnicode=false&amp;characterEncoding=utf8
    username: root
    password: 123

mybatis:
  #扫描对应的文件
  mapper-locations: classpath:cn/it/Mapper/*.xml
  #取别名
  type-aliases-package: cn.it.domain
  #驼峰命名方式
  configuration:
    mapUnderscoreToCamelCase: true
    #日志扫描
logging:
  level:
    cn:
      it: trace
  root: error
